# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHaI9sexi2QCzogPH7SS28aknVznG75u
"""

import pandas as pd
baza={
    "FISH":["Xolmatova Nilufar", "Aliyeva Ra'no", "Ibrohimova Adolatxon","Alekseyeva Xadicha ","Iminova Guli","Obidova Muhlisa","Mehmonaliyev Muhammmadaziz","Qodirov Asliddin","Olimjonov Nizomjon","Turg'unboyeva Zuhra"],
    "Yoshi":["19","20","19","19","19","19","18","19","19","18"],
    "Jinsi":["qiz bola","qiz bola","qiz bola","qiz bola","qiz bola","qiz bola","o'g'il bola","o'g'il bola","o'g'il bola","qiz bola"],
    "Qaysi unversitetda o'qishi":["TATUFF","FARDU","TATUFF","TATUFF","QDP","TATUFF","TATU","TATUFF","TATUFF","TATUFF"],
    "Manzil":["Farg'ona shahar","Samarqand shahar","Farg'ona shahar","Farg'ona shahar","Qo'qon shahar","Farg'ona shahar","Toshkent shahar","Farg'ona shahar","Farg'ona shahar","Farg'ona shahar",]
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']=="qiz bola"]
print(filtr)

filter=db[(db['Jinsi']=="qiz bola") & (db["Qaysi unversitetda o'qishi"]=="TATUFF")]
print(filter)

filter=db[(db['Jinsi']=="o'g'il bola") & (db['Manzil']=="Farg'ona shahar")]
print(filter)